export interface WordItem {
  word: string;
  category: string;
}

export const EASY_WORDS: WordItem[] = [
  { word: "GAME", category: "General" },
  { word: "PLAY", category: "General" },
  { word: "STAR", category: "Space" },
  { word: "MOON", category: "Space" },
  { word: "FIRE", category: "Nature" },
  { word: "WIND", category: "Nature" },
  { word: "ROCK", category: "Nature" },
  { word: "BIRD", category: "Animals" },
  { word: "LION", category: "Animals" },
  { word: "FROG", category: "Animals" },
  { word: "DEER", category: "Animals" },
  { word: "FISH", category: "Animals" },
  { word: "BLUE", category: "Colors" },
  { word: "PINK", category: "Colors" },
  { word: "CYAN", category: "Colors" },
  { word: "GRAY", category: "Colors" },
  { word: "TEAL", category: "Colors" },
  { word: "GOLD", category: "Colors" },
  { word: "TREE", category: "Nature" },
  { word: "LEAF", category: "Nature" },
  { word: "SAND", category: "Nature" },
  { word: "WAVE", category: "Nature" },
  { word: "COAL", category: "Nature" },
  { word: "IRON", category: "Nature" },
  { word: "SHIP", category: "Vehicles" },
  { word: "BOAT", category: "Vehicles" },
  { word: "TAXI", category: "Vehicles" },
  { word: "TRAM", category: "Vehicles" },
  { word: "BIKE", category: "Vehicles" },
  { word: "CITY", category: "Places" },
  { word: "PARK", category: "Places" },
  { word: "HOME", category: "Places" },
  { word: "CAFE", category: "Places" },
  { word: "SHOP", category: "Places" },
  { word: "FOOD", category: "Kitchen" },
  { word: "CAKE", category: "Kitchen" },
  { word: "SOUP", category: "Kitchen" },
  { word: "MILK", category: "Kitchen" },
  { word: "PEAR", category: "Kitchen" },
  { word: "PLUM", category: "Kitchen" },
  { word: "WORD", category: "General" },
  { word: "CODE", category: "Technology" },
  { word: "DATA", category: "Technology" },
  { word: "CHAT", category: "Technology" },
  { word: "LINK", category: "Technology" },
  { word: "GRID", category: "Technology" },
  { word: "USER", category: "Technology" },
  { word: "PAGE", category: "Technology" },
  { word: "HOST", category: "Technology" },
  { word: "NODE", category: "Technology" },
  { word: "CHIP", category: "Technology" },
  { word: "DISK", category: "Technology" },
  { word: "KING", category: "People" },
  { word: "HERO", category: "People" },
  { word: "BABY", category: "People" },
  { word: "CHEF", category: "People" },
  { word: "CREW", category: "People" },
];
