export interface WordItem {
  word: string;
  category: string;
}

export const HARD_WORDS: WordItem[] = [
  { word: "ACTION", category: "General" },
  { word: "AIRPORT", category: "Places" },
  { word: "ANIMAL", category: "Animals" },
  { word: "BICYCLE", category: "Vehicles" },
  { word: "CAMPUS", category: "Places" },
  { word: "CAMERA", category: "Technology" },
  { word: "CASTLE", category: "Places" },
  { word: "COCONUT", category: "Kitchen" },
  { word: "DESERT", category: "Nature" },
  { word: "DIAMOND", category: "General" },
  { word: "DOLPHIN", category: "Animals" },
  { word: "ENGINE", category: "Technology" },
  { word: "FESTIVAL", category: "General" },
  { word: "FLAMINGO", category: "Animals" },
  { word: "FOREST", category: "Nature" },
  { word: "GALAXY", category: "Space" },
  { word: "GUITAR", category: "Music" },
  { word: "HARBOR", category: "Places" },
  { word: "HEAVEN", category: "Space" },
  { word: "HISTORY", category: "General" },
  { word: "JOURNEY", category: "General" },
  { word: "JUNGLE", category: "Nature" },
  { word: "KITCHEN", category: "Places" },
  { word: "LANTERN", category: "Household" },
  { word: "LIBRARY", category: "Places" },
  { word: "MONSTER", category: "General" },
  { word: "MOUNTAIN", category: "Nature" },
  { word: "MYSTERY", category: "General" },
  { word: "OCTOPUS", category: "Animals" },
  { word: "OFFICE", category: "Places" },
  { word: "ORCHESTRA", category: "Music" },
  { word: "PAINTER", category: "People" },
  { word: "PENGUIN", category: "Animals" },
  { word: "PROJECT", category: "Technology" },
  { word: "PYRAMID", category: "Places" },
  { word: "RAINBOW", category: "Nature" },
  { word: "ROCKET", category: "Space" },
  { word: "SAILBOAT", category: "Vehicles" },
  { word: "SCULPTOR", category: "People" },
  { word: "SHADOW", category: "General" },
  { word: "SOLDIER", category: "People" },
  { word: "SPARROW", category: "Animals" },
  { word: "STADIUM", category: "Places" },
  { word: "SUBWAY", category: "Vehicles" },
  { word: "SURGERY", category: "General" },
  { word: "TEACHER", category: "People" },
  { word: "TEMPLE", category: "Places" },
  { word: "THEATER", category: "Places" },
  { word: "TORNADO", category: "Nature" },
  { word: "TOURIST", category: "People" },
  { word: "TREASURE", category: "General" },
  { word: "UNIVERSE", category: "Space" },
  { word: "VOLCANO", category: "Nature" },
  { word: "WEATHER", category: "Nature" },
  { word: "WHISPER", category: "General" },
  { word: "WIZARD", category: "People" },
  { word: "ZEPHYR", category: "Nature" },
];
