export interface WordItem {
  word: string;
  category: string;
}

export const MEDIUM_WORDS: WordItem[] = [
  { word: "ABOUT", category: "General" },
  { word: "ALERT", category: "Technology" },
  { word: "APPLE", category: "Kitchen" },
  { word: "BEACH", category: "Nature" },
  { word: "BREAD", category: "Kitchen" },
  { word: "BRICK", category: "Construction" },
  { word: "CHAIR", category: "Household" },
  { word: "CHEST", category: "Household" },
  { word: "CLOCK", category: "Household" },
  { word: "CLOUD", category: "Space" },
  { word: "CROWN", category: "People" },
  { word: "DANCE", category: "General" },
  { word: "DRAFT", category: "General" },
  { word: "EARTH", category: "Space" },
  { word: "FLAME", category: "Nature" },
  { word: "FLUTE", category: "Music" },
  { word: "FRUIT", category: "Kitchen" },
  { word: "GRAPE", category: "Kitchen" },
  { word: "GREEN", category: "Colors" },
  { word: "HOUSE", category: "Places" },
  { word: "IMAGE", category: "Technology" },
  { word: "LEMON", category: "Kitchen" },
  { word: "LIGHT", category: "Nature" },
  { word: "MARCH", category: "General" },
  { word: "MONEY", category: "General" },
  { word: "MOUSE", category: "Animals" },
  { word: "MUSIC", category: "Music" },
  { word: "OCEAN", category: "Nature" },
  { word: "ORGAN", category: "Music" },
  { word: "PEACH", category: "Kitchen" },
  { word: "PHONE", category: "Technology" },
  { word: "PIANO", category: "Music" },
  { word: "PILOT", category: "People" },
  { word: "PLANT", category: "Nature" },
  { word: "PLATE", category: "Kitchen" },
  { word: "QUEEN", category: "People" },
  { word: "RADIO", category: "Technology" },
  { word: "RIVER", category: "Nature" },
  { word: "ROBOT", category: "Technology" },
  { word: "SCENE", category: "General" },
  { word: "SHARK", category: "Animals" },
  { word: "SMILE", category: "General" },
  { word: "SNAKE", category: "Animals" },
  { word: "SPACE", category: "Space" },
  { word: "STEAM", category: "Nature" },
  { word: "STONE", category: "Nature" },
  { word: "STORM", category: "Nature" },
  { word: "SUGAR", category: "Kitchen" },
  { word: "TABLE", category: "Household" },
  { word: "TIGER", category: "Animals" },
  { word: "TRAIN", category: "Vehicles" },
  { word: "TRUCK", category: "Vehicles" },
  { word: "VOICE", category: "General" },
  { word: "WATER", category: "Nature" },
  { word: "WHEEL", category: "Vehicles" },
  { word: "WORLD", category: "General" },
  { word: "WRITE", category: "General" },
  { word: "YACHT", category: "Vehicles" },
  { word: "ZEBRA", category: "Animals" },
];
