export const SOCKET_EVENTS = {
  CONNECT: "connect",
  CONNECT_ERROR: "connect_error",
  REGISTER_PLAYER: "registerPlayer",
  CREATE_ROOM: "createRoom",
  JOIN_ROOM: "joinRoom",
  REJOIN_ROOM: "rejoinRoom",
  ROOM_CREATED: "roomCreated",
  ROOM_JOINED: "roomJoined",
  REJOINED_ROOM_SUCCESS: "rejoinedRoomSuccess",
  ROOM_UPDATED: "roomUpdated",
  REMATCH_STARTED: "rematchStarted",
  ERROR_MSG: "errorMsg",
  REJOIN_FAILED: "rejoinFailed",
  TYPING_STATE_UPDATED: "typingStateUpdated",
  MAKE_MOVE: "makeMove",
  REQUEST_REMATCH: "requestRematch",
  DECLINE_REMATCH: "declineRematch",
  LEAVE_ROOM: "leaveRoom",
  LUDO_TOGGLE_READY: "ludoToggleReady",
  LUDO_START_GAME: "ludoStartGame",
  LUDO_ROLL_DICE: "ludoRollDice",
  LUDO_MOVE_TOKEN: "ludoMoveToken",
  SEND_MESSAGE: "sendMessage",
  TYPING_STATE: "typingState",
} as const;
